lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
  nextflow_config:
    - params.input
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Judith Bernett
  description: This pipeline evaluates drug response models in various settings on
    a variety of datasets.
  force: false
  is_nfcore: true
  name: drugresponseeval
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
    - multiqc
    - fastqc
  version: 1.0dev
